### ISSUE TITLE
List of packages for Fedora

### ISSUE THREAD

**Issue by ScrawnyPetauro** [brummer10/guitarix.vst#1]
Hi,

Just got it to compile successfully in Fedora37. This is the list of the packages in the same order as you listed those for Debian (if you'd like to add it to the docs). There are some exceptions:

- For `libgcc` I didn't find any dev packages, so I installed also `gcc` for good measure and it compiled okay.
- I installed all "normal" packages and dev packages
- For `boost-system` and `boost-iostreams` there is only one dev package called `boost-devel` 

Here is the list:
- freetype-devel
- glibmm2.4-devel
- glib2-devel
- libsigc++20-devel
- fftw-devel
- libsndfile-devel
- lilv-devel
- liblrdf-devel
- boost-devel
- libstdc++-devel
- glibc-devel
- libgcc
- gcc
- alsa-lib-devel
- webkit2gtk4.0-devel
- gtk3-devel
- avahi-gobject-devel
- avahi-glib-devel
- avahi-devel
- eigen3-devel

Hope this helps!

**Comment by brummer10** [comment]
Thanks a lot, added to the README file. :)
