### ISSUE TITLE
No effect when in mono, works in stereo

### ISSUE THREAD

**Issue by webaake** [brummer10/guitarix.vst#10]
Hold your horses! It seems to be working now as intended. I didn't do any changes, so don't know how.

Just compiled latest vst3 (juce) source (today's date) and it worked at first, when scanned from inside Reaper. But when restarting Reaper there was no sound although the meters in the plugin showed incoming signal. But when clicking the stereo button in the plugin- effects returned. Weird. Disappeared again when clicking back to mono. In mono it was just the original guitar signal without effects.

Is there something I can do? Some setting somewhere?

Reaper 6.73.xxx.dev.xxx, Devuan 4. jjcale_guitar on Reaper forums.

By the way, this seems to be the best guitar plugin I've ever seen.

**Comment by brummer10** [comment]
Hi. 
Good to hear it works (at least). 
Many thanks for your donation. 
regards
hermann
