### ISSUE TITLE
Closing and reopening the GUI changes the order of the rack units

### ISSUE THREAD

**Issue by kramlie** [brummer10/guitarix.vst#11]
If you have one unit above the amp stack and one below, and you close the GUI and reopen it, the upper one gets moved to below the amp stack. The sound doesn't change until you touch one of the controls in the misplaced unit though. If you close the project completely and reopen, then the order is correct upon the first open, but again wrong on the second open.

Tested on Linux in both Renoise and Carla.

**Comment by brummer10** [comment]
Hi
Thanks for reporting. I could reproduce it and will push a fix soon.

**Comment by brummer10** [comment]
Okay, I've pushed a fix for that to the repository. Let me know if it works for you as well.
regards
hermann
