### ISSUE TITLE
Fuzz Master unstable

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix.vst#12]
I have found another effect not functional while trying the Musiclab presets: the Fuzz Master. It immediately dies in static (only tested it at 96khz). This is very low priority as I don't particularly need it, just letting you know.

**Comment by brummer10** [comment]
Ah, yes, I see. This is one of the early ones generated with the dk builder. I need to rework it to make it suitable for 96kHz.
Thanks for head up.

**Comment by brummer10** [comment]
I've disabled the Fuzz Master plug now for the vst version.
