### ISSUE TITLE
Menus are very hard to use in the UI

### ISSUE THREAD

**Issue by ssssam** [brummer10/guitarix.vst#15]
Testing with Bitwig Studio via Flatpak on Fedora 39, commit 33e598690f83873c91642d2601e5e33ff9db6dee of guitarix.vst and commit 80e951fb3212c058c507c421cecfacca1f6d2932 of guitarix.

Selecting menu items using the mouse is very difficult as the menu sometimes flickers in and out of existence after just one mouse click.

Here's a 30 second video showing the issue. It gets more obvious towards the end. I'm not doing anything weird with the mouse clicks, just clicking once each time to open the menu, which sometimes works and sometimes doesn't. When you see the menu flicker on and off quickly, that's the bug.

[Screencast from 2024-02-11 18-36-01.webm](https://github.com/brummer10/guitarix.vst/assets/6330/74d782c0-3230-4b5c-8184-c1b9fd1562c5)

Separate issue I guess, but mousing through small menus is quite annoying - it would make this easier to add keyboard shortcuts and/or a "Next" button to navigate through the menus. Or perhaps I can MIDI map this somehow - need to investigate.

**Comment by brummer10** [comment]
I've pushed a fix for it to the repository. The popup menus will now popup on button release, this avoid that the menu is already visible while the mouse button is still pressed and then disappear when the mouse release.

**Comment by brummer10** [comment]
This is now fixed in the latest release.
