### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by billyblackburn** [brummer10/guitarix.vst#16]
Do y'all plan on adding any nam type modelling to the guitarix stack ..it would be really cool to have physical and neural modeling in one vst.  Y'all's physical modelling is great

**Comment by billyblackburn** [comment]
ok, s o i installed the vst3 wrapper and tried it with Renoise.....i really like the UI, and I did see the lv2 plugins which is super cool feature, but maybe we can work together to allow the nam lv2 plugin to be visible to Guitarix.  ..the reason this is so cool for me is that Renoise is my main DAW and it doesn't have lv2 support natively.  and, the new GUI is much better than a carla rack....especially for guitartists....nice work yall

**Comment by brummer10** [comment]
I'm glad you like it. Well, I'll work on add NAM support in guitarix. Still I'm not sure if I would go the full LV2 path, or implement it as alternative amp in the current amp selector. 
However, you could use the Neural Amp Modeller LV2 plug (you need the GUI I made) in renoise by wrapping it with lv2vst https://github.com/x42/lv2vst
just build it, create a new folder in your  vst folder $HOME/.vst and copy it over to there. Create a file ".whitelist" there and enter the NAM url 
http://github.com/mikeoliphant/neural-amp-modeler-lv2
save it and be done. You could now load it into renoise as vst plug:
![2024-02-13_04-57](https://github.com/brummer10/guitarix.vst/assets/2683982/621b54d9-25af-4b7e-9391-efb24119dd15)

**Comment by brummer10** [comment]
So I've NAM running as internal plug in guitarix already. Needs some day's to make it production ready.
