### ISSUE TITLE
"/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found" when trying .vst3 in Ardour

### ISSUE THREAD

**Issue by Brainpiercing** [brummer10/guitarix.vst#18]
Hi! I would love to try your Guitarix VST3, but when I scan the plugin with Ardour that error message comes up. 

"/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found"

I tried googling all over, but couldn't find a solution to this, even though this particular error occurs with multiple different packages, at least there are dozens of results.
I don't know what to do about my  libstdc++6 version, it's the most current one according to synaptic, 10.5.0-1ubuntu1-20.04. It only provides up to GLIBCXX_3.4.28 

I'm running Ubuntu Studio 20.04. 

Any pointers? I have all the other dependencies. Could I build from source without that requirement?

**Comment by brummer10** [comment]
You could add this ppa https://launchpad.net/~ubuntu-toolchain-r and install libstdc++6 from there
(That's what happen on the github service and I didn't find a way to avoid that)
or, you could run
`sudo apt-get install libcurl4-gnutls-dev libfreetype6-dev libglibmm-2.4-dev libglib2.0-dev libsigc++-2.0-dev libfftw3-dev libsndfile1-dev liblilv-dev liblrdf0-dev libboost-iostreams-dev libstdc++6 libc6-dev libgcc-s1 libasound2-dev libgtk-3-dev libavahi-gobject-dev libavahi-glib-dev libavahi-client-dev libeigen3-dev libboost-system-dev`

to install the dependencies and build it yourself. 
There is no deep dependency to a more recent libstdc++6 version then yours.
But note, there is currently a unresolved issue with the official Ardour releases, leads to crash on session reload.
 https://github.com/brummer10/guitarix.vst/issues/17

**Comment by Brainpiercing** [comment]
Great stuff! Thanks!! I'll give it a spin then!
(And Ardour issue hopefully won't be a problem as I'm still on 8.2...)

**Comment by Brainpiercing** [comment]
Hmm, I downloaded the latest 0.2 binary and it still gives me the GLIBCXX error :/

**Comment by brummer10** [comment]
Are you sure you've removed the older one and installed (copied) the new one?
I've just checked it again and pretty sure it used the stock standard libstdc++ version from ubuntu 20.4
 https://github.com/brummer10/guitarix.vst/actions/runs/8022387728/job/21916590721#step:5:42

I also checked the binary with
readelf -Ws '/path/to/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so' | grep GLIBCXX

the highest version linked in is GLIBCXX_3.4.26

**Comment by Brainpiercing** [comment]
The readelf gives me no reference to 3.4.30, just 3.4.26 as you said.

I've now also compiled from the source code, with no error message about GLIBCXX, deleted the precompiled binary, did make install, and as of now, Carla can run the VST3. Yay!

But Ardour plugin scan STILL gives me that error message. Maybe it's Ardour that's the problem? But how?

**Comment by brummer10** [comment]
Nice to hear. 
Hope you enjoy guitarix.vst.
