### ISSUE TITLE
[ERROR]: libcurl-gnutls.so.4: cannot open

### ISSUE THREAD

**Issue by ManuLinares** [brummer10/guitarix.vst#19]
[ERROR]: Could not load VST3 plugin '/home/mb/.vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so': libcurl-gnutls.so.4: cannot open

When loading on Ardour 8.4.0
Using Archlinux

Fixed by installing "libcurl-gnutls" package.

Maybe list it as "required" for a new section "Arch"?

**Comment by brummer10** [comment]
Hi
Thanks for the hint. Still, it is listed under the dependencies on the project-page.  
https://github.com/brummer10/guitarix.vst?tab=readme-ov-file#dependencies

I guess I'll remove the lists for fedora and open suse and write something like

"on other distros the dependencies been the same, the packages may have different but most similar names"

instead maintain a list for every distro.
