### ISSUE TITLE
Two vst entries in Ardour, one breaks the DAW

### ISSUE THREAD

**Issue by ScrawnyPetauro** [brummer10/guitarix.vst#2]
Hey again!

So, Ardour imports the vst correctly, but then I see two instances (see screenshot below). 

If I select the first instance, it works fine. If I select the second instance, it makes Ardour crash.

![image](https://user-images.githubusercontent.com/32942578/210175193-63049885-648c-40d8-bf8f-2d74725932ee.png)

**Comment by brummer10** [comment]
Nice to hear it works!
But strange. should indeed only be one entry. Please check if you've something strange in your ~/.vst3 directory. There should as well only be one Guitarix.vst3 folder.

**Comment by ScrawnyPetauro** [comment]
Nevermind, I indicated the folder where I had compiled the vst as a location for the vst3 plugins, hence the double entry. I've taken it off and it's behaving as expected now!
