### ISSUE TITLE
kxstudio lv2-dev incompatible for building from source (solution included, not mine)

### ISSUE THREAD

**Issue by Brainpiercing** [brummer10/guitarix.vst#20]
As the title says: 
The kxstudio lv2-dev (1.18.10-kxstudio) changes the folder structure in /usr/include/lv2 and there is an error message about presets.h missing. 

Solution:
Downgrade lv2-dev to the one included in the distro. (1.16)

source for solution here, also guitarix related:
https://linuxmusicians.com/viewtopic.php?t=26365

Solution for dummies like me:
Force version in Synaptic to 1.16, Apply. Then build.

**Comment by brummer10** [comment]
Thanks for the reminder. 
I've fixed that now in the guitarix source so that it should work with both versions of the lv2-dev package.
