### ISSUE TITLE
Plugin cannot be loaded in latest Ardour nightly 8.6.72

### ISSUE THREAD

**Issue by axel-rank** [brummer10/guitarix.vst#24]
Error:

```
2024-04-30T11:44:11 [ERROR]: Could not load VST3 plugin '/usr/lib/vst3/Guitarix.vst3/Contents/x86_64-linux/Guitarix.so': /usr/lib/libavahi-gobject.so.0: undefined symbol: g_once_init_enter_pointer
```

**Comment by brummer10** [comment]
Is that the latest revision from the repository? 
I've removed avahi support from the vst3 plug last month, just didn't make a release. 
Still, the last binary should be come without the need to avahi.

**Comment by axel-rank** [comment]
Guitarix.vst v0.3 Release from March 11

**Comment by brummer10** [comment]
You may switch to the git version to overcome this issue:
https://aur.archlinux.org/packages/guitarix.vst-git

I don't know when I could make a new release.

**Comment by axel-rank** [comment]
Yes, git version working. Thanks.
