### ISSUE TITLE
No GUI after building from source on Raspberry Pi OS (64-bit Bookworm)

### ISSUE THREAD

**Issue by GuntherT** [brummer10/guitarix.vst#29]
I successfully built guitarix.vst on Raspberry Pi OS using both the v0.3 source code and the latest git.  In both instances, whether I used the included JUCE modules or the system modules, there is no GUI when opened in Ardour 8.6, which I installed via the binary from ardour.org.  I also tried a copy of Ardour installed via the apt repositories, which provided version 7.3, but I encountered the same issue.  There were no build errors or messages from Ardour that pointed to the source of the problem.  After each of the four rounds of building guitarix.vst, I removed  the non-functional instance before starting over, so I believe I have properly tested all four build methods [v0.3 with included modules, v0.3 with system modules, latest git with included modules, latest git with system modules].  Let me know if you need more information or would like me to test anything on my end.

```
pidaw@raspberrypi:~/guitarix.vst $ make
INFO: Submodule up to date
INFO: Using included Juce modules [../../JuceModules]
INFO: optimised for aarch64
INFO: Compiling modules - done
Linking Guitarix - Shared Code
Linking Guitarix - VST3
Stripping Guitarix - VST3
INFO: Build finish, now run make install

pidaw@raspberrypi:~/guitarix.vst $ make USE_SYSTEM_JUCE=1
INFO: Submodule up to date
INFO: Using system Juce modules [/usr/share/juce]
INFO: optimised for aarch64
INFO: Compiling modules - done
Linking Guitarix - Shared Code
Linking Guitarix - VST3
Stripping Guitarix - VST3
INFO: Build finish, now run make install
```

**Comment by brummer10** [comment]
It's a pitta.
You could try juce version 7.0.5 which seems to work for most people here. 
https://github.com/brummer10/guitarix.vst/issues/13#issuecomment-2293181069
`make JUCE_DIR=/path/to/juce `

**Comment by GuntherT** [comment]
The updated JUCE modules solved it.  The GUI is now functioning after building version 0.4.  Thank you!
