### ISSUE TITLE
Bitwig: Could not read repsonses: End of stream

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix.vst#32]
Hi Hermann,

After a good while without seeing it, this error comes again quite regularly on startup, so it is time for a bug report.

The behavior:
- It doesn't happen every time
- only on startup
- several projects are affected
- Bitwig recovers quite nicely (plugins are sandboxed) and this is usually fixed by hitting the "reload all plugins" button
- happens as of guitarix.vst-git-v0.3.r6.g1904d72-1-x86_64 / guitarix-git-0.46.0.r12
- I usually have 3-4 guitarix-vst instances loading NAM models (all of them)
- the neighbors: Odin and Surge XT

Here's what I managed to catch from Bitwig's engine.log

> [2024-9-21 19:0:18.753 BITWIG_ENGINE error] Could not read repsonses: End of stream
> [2024-9-21 19:0:18.754 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 19:0:18.782 BITWIG_PLUGIN_HOST error] PluginHost: Client died: Could not send responses to client: Error writing to named pipe: Broken pipe
> 

A bit more verbose:
> [2024-9-21 18:14:20.816 BITWIG_ENGINE info] Creating plugin audio thread proxy 0
> [2024-9-21 18:14:20.816 BITWIG_PLUGIN_HOST info] PluginHost: Starting new audio thread for processing plugin 0
> [2024-9-21 18:14:20.828 BITWIG_PLUGIN_HOST info] About to create a VST 3 plugin instance for ABCDEF019182FAEB4D616E754C736166 (/usr/lib/vst3/Guitarix.vst3)
> [2024-9-21 18:14:20.963 BITWIG_PLUGIN_HOST info] PluginHost: Loading initial plugin state: /home/gimmeapill/.BitwigStudio/plugin-states/9d275a9a-0263-4dea-bef4-032a824b5fd3.vstpreset
> [2024-9-21 18:14:22.023 BITWIG_ENGINE error] Could not read repsonses: End of stream
> [2024-9-21 18:14:22.023 BITWIG_ENGINE info] Killing pluginhost process
> [2024-9-21 18:14:22.023 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 18:14:22.024 BITWIG_ENGINE info] Plugin host process exited with code: 134
> [2024-9-21 18:14:22.024 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 18:14:22.024 BITWIG_ENGINE info] Plugin host process exited with code: 134
> [2024-9-21 18:14:26.017 BITWIG_ENGINE info] About to start the following process:  /opt/bitwig-studio/bin/BitwigPluginHost-X64-SSE41 host brummer-Guitarix 38354-6 6 96000 256 not-dpi-aware 32814
> [2024-9-21 18:14:26.017 BITWIG_ENGINE info] Child process launched with PID 38568
> [2024-9-21 18:14:26.024 BITWIG_ENGINE info] Plug-in host process successfully initialized
> [2024-9-21 18:14:26.024 BITWIG_ENGINE info] Creating plugin audio thread proxy 0
> [2024-9-21 18:14:26.024 BITWIG_PLUGIN_HOST info] PluginHost: Starting new audio thread for processing plugin 0
> [2024-9-21 18:14:26.036 BITWIG_PLUGIN_HOST info] About to create a VST 3 plugin instance for ABCDEF019182FAEB4D616E754C736166 (/usr/lib/vst3/Guitarix.vst3)
> [2024-9-21 18:14:26.175 BITWIG_PLUGIN_HOST info] PluginHost: Loading initial plugin state: /home/gimmeapill/.BitwigStudio/plugin-states/e2c90a6c-8f5a-4a33-b35c-5df967a9e592.vstpreset
> [2024-9-21 18:14:27.447 BITWIG_ENGINE info] Creating plugin audio thread proxy 1
> [2024-9-21 18:14:27.448 BITWIG_PLUGIN_HOST info] PluginHost: Starting new audio thread for processing plugin 1
> [2024-9-21 18:14:27.448 BITWIG_PLUGIN_HOST info] About to create a VST 3 plugin instance for ABCDEF019182FAEB4D616E754C736166 (/usr/lib/vst3/Guitarix.vst3)
> [2024-9-21 18:14:27.592 BITWIG_PLUGIN_HOST info] PluginHost: Loading initial plugin state: /home/gimmeapill/.BitwigStudio/plugin-states/b08074f0-6069-4e43-a27a-4d7007b71faf.vstpreset
> [2024-9-21 18:14:29.195 BITWIG_ENGINE info] Creating plugin audio thread proxy 2
> [2024-9-21 18:14:29.196 BITWIG_PLUGIN_HOST info] PluginHost: Starting new audio thread for processing plugin 2
> [2024-9-21 18:14:29.196 BITWIG_PLUGIN_HOST info] About to create a VST 3 plugin instance for ABCDEF019182FAEB4D616E754C736166 (/usr/lib/vst3/Guitarix.vst3)
> [2024-9-21 18:14:29.346 BITWIG_PLUGIN_HOST info] PluginHost: Loading initial plugin state: /home/gimmeapill/.BitwigStudio/plugin-states/7132ea1f-879e-4738-afe1-4c93e4eae39d.vstpreset
> [2024-9-21 18:14:30.931 BITWIG_ENGINE info] Creating plugin audio thread proxy 3
> [2024-9-21 18:14:30.932 BITWIG_PLUGIN_HOST info] PluginHost: Starting new audio thread for processing plugin 3
> [2024-9-21 18:14:30.932 BITWIG_PLUGIN_HOST info] About to create a VST 3 plugin instance for ABCDEF019182FAEB4D616E754C736166 (/usr/lib/vst3/Guitarix.vst3)
> [2024-9-21 18:14:31.081 BITWIG_PLUGIN_HOST info] PluginHost: Loading initial plugin state: /home/gimmeapill/.BitwigStudio/plugin-states/9d275a9a-0263-4dea-bef4-032a824b5fd3.vstpreset
> [2024-9-21 18:35:31.791 BITWIG_PLUGIN_HOST brummer Guitarix info] Closing plug-in undo history file
> [2024-9-21 19:0:18.657 BITWIG_ENGINE info] Starting processing for device Dummy Silent Device for Project 10...
> [2024-9-21 19:0:18.657 BITWIG_ENGINE info] Started processing for device Dummy Silent Device for Project 10
> [2024-9-21 19:0:18.657 BITWIG_ENGINE info] Engine switched to device Dummy Silent Device for Project 10
> [2024-9-21 19:0:18.657 BITWIG_ENGINE info] Disconnecting from project 10
> [2024-9-21 19:0:18.664 BITWIG_ENGINE info] Stopping processing for device Dummy Silent Device for Project 10...
> [2024-9-21 19:0:18.665 BITWIG_ENGINE info] Stopped processing for device Dummy Silent Device for Project 10
> [2024-9-21 19:0:18.665 BITWIG_ENGINE info] Closing device Dummy Silent Device for Project 10...
> [2024-9-21 19:0:18.700 BITWIG_ENGINE info] Scheduling project delete
> [2024-9-21 19:0:18.700 BITWIG_ENGINE info] Deleting project
> [2024-9-21 19:0:18.701 BITWIG_ENGINE info] Sending a shutdown request to the plugin host
> [2024-9-21 19:0:18.702 BITWIG_PLUGIN_HOST info] PluginHost: Destroying plugin with id 1
> [2024-9-21 19:0:18.711 BITWIG_PLUGIN_HOST info] PluginHost: Shutting down...
> [2024-9-21 19:0:18.711 BITWIG_PLUGIN_HOST info] PluginHost: About to unload plugin /usr/lib/vst3/Odin2.vst3
> [2024-9-21 19:0:18.711 BITWIG_PLUGIN_HOST info] PluginHost: Unloading plugin /usr/lib/vst3/Odin2.vst3
> [2024-9-21 19:0:18.712 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 19:0:18.718 BITWIG_PLUGIN_HOST info] PluginHost: Shutting down request reader thread
> [2024-9-21 19:0:18.718 BITWIG_PLUGIN_HOST info] PluginHost: Request reader thread finished
> [2024-9-21 19:0:18.718 BITWIG_PLUGIN_HOST info] PluginHost: Shutting down audio threads
> [2024-9-21 19:0:18.718 BITWIG_PLUGIN_HOST info] PluginHost: Exiting due to shutdown
> [2024-9-21 19:0:18.718 BITWIG_PLUGIN_HOST info] PluginHost: exiting with code 0
> [2024-9-21 19:0:18.720 BITWIG_ENGINE info] Plugin host process exited with code: 0
> [2024-9-21 19:0:18.720 BITWIG_PLUGIN_HOST info] PluginHost: Destroying plugin with id 1
> [2024-9-21 19:0:18.721 BITWIG_ENGINE info] Sending a shutdown request to the plugin host
> [2024-9-21 19:0:18.753 BITWIG_PLUGIN_HOST info] PluginHost: Destroying plugin with id 2
> [2024-9-21 19:0:18.753 BITWIG_ENGINE error] Could not read repsonses: End of stream
> [2024-9-21 19:0:18.754 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 19:0:18.782 BITWIG_PLUGIN_HOST error] PluginHost: Client died: Could not send responses to client: Error writing to named pipe: Broken pipe
> [2024-9-21 19:0:18.783 BITWIG_PLUGIN_HOST info] PluginHost: exiting with code 1
> [2024-9-21 19:0:18.797 BITWIG_ENGINE error] Child process with PID 38568 exited with error code: 1
> [2024-9-21 19:0:18.798 BITWIG_ENGINE info] Plugin host process exited with code: 256
> [2024-9-21 19:0:18.805 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 19:0:18.805 BITWIG_ENGINE info] Plugin host process exited with code: 0
> [2024-9-21 19:0:18.807 BITWIG_ENGINE info] Waiting for plugin host process to exit
> [2024-9-21 19:0:18.807 BITWIG_ENGINE info] Plugin host process exited with code: 256
> [2024-9-21 19:0:18.810 BITWIG_ENGINE info] Project deleted
> [2024-9-21 19:0:18.811 BITWIG_ENGINE info] Project disconnecting from has been deleted
> [2024-9-21 19:0:18.814 BITWIG_ENGINE info] Disconnected from project
> ...

**Comment by brummer10** [comment]
I've a idea what the culprit is . . .

**Comment by brummer10** [comment]
Maybe the last commit fix it? As I've a other report were the last commit fix the crash.
https://github.com/brummer10/guitarix.vst/issues/30

**Comment by Gimmeapill** [comment]
I'm not using any stereo input, but I'll rebuild and report back. 
I'll try to resave all the presets involved also, in case that could be related

**Comment by Gimmeapill** [comment]
Good news: 2 weeks and the issue didn't reoccur.
I think we can consider this one fixed - thanks Hermann!
