### ISSUE TITLE
JCM800 randomly stops working

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix.vst#4]
I got two occurrences of the JCM800 stopping to produce any sound in Bitwig. 
The vst plugin itself didn't crash (I could open other presets), but I had to close the document an reopen for the JCM to get back to work. Unfortunately I couldn't gather any meaningful information. The git revision: r0.g9dc30ea
I tried to let it run for ~8 hours non stop without the problem occurring, so this is really random.
This is if I remember correctly an old Guitarix issue that could never be completely fixed.
I couldn't find any existing report on github, so opening a new one...

**Comment by brummer10** [comment]
Yes, the JCM800 isn't really stable at all. It hardly depend on optimization levels from the compiler which indicate that there is a problem. ( On levels below  -O3 it wouldn't work at all)
I haven't implemented any more optimization flags in the makefile right now, doing that will stabilize it a bit more.
I'll ping here when I've implemented optimization flags for the vst.

**Comment by Gimmeapill** [comment]
In case that helps, I managed to have it crash quite reliably in Bitwig by adding 2 instances, loading patches that contain the JCM800, saving and reopening the document. There's just a glitch noise on startup and the instances don't produce any sound until I change the preset.

**Comment by brummer10** [comment]
Yes, the JCM800 use a lot of static variables, that needs to be reworked.

**Comment by maexwellius** [comment]
Also a quite reliable crash in Reaper is adding two tracks containing JCM800 in presets. I need to redo my presets without JCM800.

**Comment by brummer10** [comment]
I've disabled the JCM800 plug now for the vst version.

**Comment by maxlystifidelix** [comment]
Workaround: There should be no issues using multiple instances of JCM800 as standalone effect in fx chains?
Struggling to find as good sounding plugins.

**Comment by maexwellius** [comment]
As a workaround there should be no issues using multiple instances of JCM800 as standalone effect in fx chains?
Struggling to find as good sounding plugins.

**Comment by brummer10** [comment]
you could now use neural models from NAM or AIDA-X
