### ISSUE TITLE
UI scale relative to the Ardour's GUI

### ISSUE THREAD

**Issue by cooltehno** [brummer10/guitarix.vst#6]
Hello! 
During playing the Guitarix plugin inside Ardour DAW I've noticed that the Guitarix changes it's scale dependently on the Ardour's UI scaling. If it is possible  to make GX UI independent scale from Ardour - that could be more comfortable (IMHO). For example if I increase Ardour GUI more than 150% - the GX UI can't match the monitor (for notebook 150% Ardour's scale not enough sometimes):
 
![UI_scale_150_200](https://user-images.githubusercontent.com/19673308/216964985-ff71eec8-82a1-4c95-b091-425d60f9e1a5.png)
Thank you for GX! :zap:

**Comment by brummer10** [comment]
Hmm, the window display the plugin is owned by Ardour, the plugin itself just react on the given size (in case it doesn't match the requested one), so I don't know if I could fix that.

**Comment by brummer10** [comment]
Hi @cooltehno 
I've made the UI now freely scalable, so you could resize it to your needs.
It will still react on Ardours scale settings, but you could resize it when needed.
