### ISSUE TITLE
Thick distortion volume hangs the UI

### ISSUE THREAD

**Issue by kramlie** [brummer10/guitarix.vst#9]
When trying to control the Thick distortion volume knob, it quickly goes to a "nan" number, and then freezes the UI. The effect still works though, but the UI is uncontrollable after that. I'm using Ubuntu 22.04 64-bit, host is Renoise, and the commit is 22dcdcf0c18d3f44bf154c0cef701e8ef5168b5d.

**Comment by brummer10** [comment]
Thanks for reporting the issue. It should be fixed now in latest revision.

**Comment by kramlie** [comment]
Confirmed! Thanks for the quick fix, case closed!
